name: Deploy to Vultr

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # - Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      # - Setup Docker Buildx (required for caching)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # - Build & Push BACKEND image
      - name: Build & push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/00tanveer/stories-backend:latest

      # - Build & Push FRONTEND image
      - name: Build & push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/00tanveer/stories-frontend:latest
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            VITE_PUBLIC_POSTHOG_KEY=${{ secrets.VITE_PUBLIC_POSTHOG_KEY }}
            VITE_PUBLIC_POSTHOG_HOST=${{ secrets.VITE_PUBLIC_POSTHOG_HOST }}

      # - SSH into Vultr & deploy containers
      - name: Pull & restart containers on Vultr
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VULTR_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /opt/stories/
            git pull origin main
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
      # - Notify on Discord server about the deployment status
      - name: Notify Discord on success
        if: success()  # only runs if every step succeeded
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"üöÄ Deployment to Vultr successful for commit: $GITHUB_SHA\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: Notify Discord on failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"‚ùå Deployment FAILED on commit: $GITHUB_SHA\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
